name: 'Split Packages'
on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  split_packages:
    if: >
      (  github.event_name == 'workflow_run' &&
         github.event.workflow_run.event == 'push' &&
         github.event.workflow_run.conclusion == 'success'
      ) || github.event_name != 'workflow_run'
    runs-on: ubuntu-latest
    name: 'Split Packages'
    strategy:
      matrix:
        package:
          -
            local_path: 'packages/framework'
            split_repository: 'framework'
          -
            local_path: 'packages/dic'
            split_repository: 'di'
          -
            local_path: 'packages/wake'
            split_repository: 'wake'
          -
            local_path: 'apps/basic-skeleton'
            split_repository: 'basic-app-skeleton'
    steps:
      - uses: actions/checkout@v4
      - run: .github/split-preprocess.sh
      # no tag
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: danharrin/monorepo-split-github-action@v2.3.0
        with:
          package_directory: ${{ matrix.package.local_path }}
          repository_organization: outboardphp
          repository_name: ${{ matrix.package.split_repository }}
          branch: main
          user_name: Garrett W.
          user_email: ${{ secrets.COMMIT_EMAIL }}
      # with tag
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: danharrin/monorepo-split-github-action@v2.3.0
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: '${{ matrix.package.local_path }}'
          repository_organization: outboardphp
          repository_name: ${{ matrix.package.split_repository }}
          branch: main
          user_name: Garrett W.
          user_email: ${{ secrets.COMMIT_EMAIL }}
